version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://backend:3000
    ports:
      - "3001:80"
